"""
Signal 1 — Groq LLM semantic classifier.

Calls Groq's chat completions API with a structured prompt that asks the
model to return a JSON object containing:
    score     float 0-1  (probability of AI authorship)
    rationale string     (plain-English explanation)
    flags     list[str]  (specific signals observed)

Requires GROQ_API_KEY in environment.
"""

import os
import json
import logging
import requests

logger = logging.getLogger(__name__)

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "llama3-8b-8192"
REQUEST_TIMEOUT = 15  # seconds

SYSTEM_PROMPT = """You are a content provenance classifier. Your job is to
assess whether a piece of text was written by a human or generated by an AI
language model.

Analyse the text for:
- Semantic richness: does it have genuine specificity, idiosyncratic opinions,
  and personal stakes? Or is it generic and hedged?
- Structural patterns: does it follow the classic AI essay structure
  (intro → numbered points → conclusion)?
- Voice consistency: does the voice feel lived-in, or does it shift into
  authoritative but hollow register?
- Epistemic markers: does the author express genuine uncertainty, or the
  performative uncertainty typical of LLMs ("It is worth noting...")?

Respond ONLY with a JSON object. No markdown, no preamble. Exactly this shape:
{
  "score": <float 0.0-1.0, where 1.0 = certainly AI>,
  "rationale": "<one or two plain-English sentences explaining the verdict>",
  "flags": ["<specific signal 1>", "<specific signal 2>"]
}"""


def classify(text: str) -> dict:
    """
    Returns:
        score     — float 0-1, probability of AI authorship
        rationale — string explanation
        flags     — list of observed signals
    Raises:
        RuntimeError if the API call fails or returns unparseable JSON.
    """
    api_key = os.environ.get("GROQ_API_KEY", "")
    if not api_key:
        logger.warning("GROQ_API_KEY not set — returning stub Signal 1 result")
        return _stub_result(text)

    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text[:4000]},  # guard context window
        ],
        "temperature": 0.0,
        "max_tokens": 256,
        "response_format": {"type": "json_object"},
    }

    try:
        resp = requests.post(
            GROQ_API_URL,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=REQUEST_TIMEOUT,
        )
        resp.raise_for_status()
    except requests.RequestException as exc:
        raise RuntimeError(f"Groq API request failed: {exc}") from exc

    raw = resp.json()["choices"][0]["message"]["content"]
    try:
        result = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Groq returned non-JSON: {raw!r}") from exc

    return {
        "score": float(result.get("score", 0.5)),
        "rationale": str(result.get("rationale", "")),
        "flags": list(result.get("flags", [])),
    }


# ---------------------------------------------------------------------------
# Stub used when GROQ_API_KEY is absent (development / testing)
# ---------------------------------------------------------------------------

def _stub_result(text: str) -> dict:
    """
    Heuristic stub so the server runs without a Groq key.
    Uses a very simple word-count check — not production quality.
    """
    words = text.lower().split()
    ai_phrases = [
        "furthermore", "moreover", "in conclusion", "it is worth noting",
        "it is important to", "additionally", "consequently",
    ]
    hits = sum(1 for p in ai_phrases if p in text.lower())
    score = min(0.9, 0.3 + hits * 0.12)
    return {
        "score": round(score, 4),
        "rationale": "[STUB — no GROQ_API_KEY] Heuristic score based on transition phrase frequency.",
        "flags": [f"transition phrase detected: '{p}'" for p in ai_phrases if p in text.lower()],
    }
